"""
Django settings for NP project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PRODUCTION_MODE = os.getenv('PRODUCTION_MODE', 'local')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ivj2nwdhabo25f7x*^_n8*-gw+%_dg0=2ggh%5z_r*%c7av3&*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if PRODUCTION_MODE in ['production'] else True

ALLOWED_HOSTS = [
    '192.168.43.186','www.navprayas.in','navprayas.in','127.0.0.1','localhost','0.0.0.0','herokuapp.navprayasweb.com',
    'navprayasdev.herokuapp.com'
]


# Application definition

INSTALLED_APPS = [
    'navprayas',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms'
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# creating folders for db
db_path = os.path.join(BASE_DIR, 'db', PRODUCTION_MODE)
if not os.path.exists(db_path):
    os.makedirs(db_path)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR,'db', PRODUCTION_MODE, 'db.sqlite3'),
        'TIME_ZONE': 'Asia/Calcutta'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# email
# run > python -m smtpd -n -c DebuggingServer localhost:1025
#EMAIL_HOST = 'localhost'
#EMAIL_PORT = 1025

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/


LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True

USE_TZ = True

TIME_ZONE =  'Asia/Calcutta'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'nstatic/'
LOGIN_REDIRECT_URL = 'index'
LOGIN_URL = 'login'

LOGOUT_REDIRECT_URL = '/index/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Needed to be written explicitly since Django 3.2
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

LAST_MODIFIED = os.getenv('last_modified')

if PRODUCTION_MODE in ['development', 'production']:
    print('using production settings')
    from NP.settings_env import *
else:
    print('using local settings')
    from NP.settings_local import *

